version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha_teste
      MYSQL_DATABASE: wallet
      MYSQL_USER: user_teste
      MYSQL_PASSWORD: senha_teste
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    command: >
      rabbitmq-server
      --no-deprecated
      --queue SET_BALANCE

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: ../Dockerfile
    working_dir: /usr/src/app
    ports:
      - 3000:3000

  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: ../Dockerfile
    depends_on:
      - mysql
    working_dir: /usr/src/app

  account-service:
    container_name: account-service
    build:
      context: ./account-service
      dockerfile: ../Dockerfile
    depends_on:
      - mysql
      - rabbitmq
    working_dir: /usr/src/app

  statement-service:
    container_name: statement-service
    build:
      context: ./statement-service
      dockerfile: ../Dockerfile
    depends_on:
      - mysql
      - rabbitmq
    working_dir: /usr/src/app

volumes:
  mysql_data:
  logs-folder:
    name: ${log_rabbitmq_management}
    driver: local
