version: "3.9"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha_teste
      MYSQL_DATABASE: wallet
      MYSQL_USER: user_teste
      MYSQL_PASSWORD: senha_teste
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
