version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql_
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha_teste
      MYSQL_DATABASE: wallet
      MYSQL_USER: user_teste
      MYSQL_PASSWORD: senha_teste
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER = admin
      - RABBITMQ_DEFAULT_PASS = passw123
    ports:
      - 25672:25672
      - 15672:15672
    volumes:
      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/

volumes:
  mysql_data:
  logs-folder:
    name: ${log_rabbitmq_management}
    driver: local
